<a href="https://colab.research.google.com/github/AmrinKareem/PyTorch-DeepLearning/blob/main/00_PyTorch_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

The first part of the course. We learn how to work with tensors and how to manipulate them.

In [ ]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
print(torch.__version__)


1.13.0+cu116


## Creating Tensors
We create tensors using torch.Tensor()

In [ ]:
#scalar
scalar = torch.tensor(7)
scalar


tensor(7)

In [ ]:
# Scalars have no dimensions
scalar.ndim

0

In [ ]:
# Get tensor back as python integer
scalar.item()

7

In [ ]:
# Now create a vector
vector = torch.tensor([7,7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
#Creating a MATRIX
MATRIX = torch.tensor([[7,8], 
                       [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX[1]

tensor([ 9, 10])

In [ ]:
MATRIX[0]

tensor([7, 8])

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
#TENSOR

TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
## Random Tensors
# Create a random tensor of shape(3,4)
random_tensor = torch.rand(3,4)


In [ ]:
random_tensor

tensor([[0.8047, 0.4850, 0.2090, 0.4781],
        [0.3203, 0.4908, 0.7512, 0.6384],
        [0.5891, 0.3456, 0.3364, 0.2793]])

In [ ]:
# Create a random tensor with shape of an image
random_image_tensor = torch.rand(size =(224,224,3))
random_image_tensor.shape, random_image_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [ ]:
rrr = random_tensor[:,2]

## Zeros and Ones

In [ ]:
zeros = torch.zeros(3,1)
zeros

tensor([[0.],
        [0.],
        [0.]])

In [ ]:
ones = torch.ones(2,2)
ones

tensor([[1., 1.],
        [1., 1.]])

In [ ]:
ones.dtype

torch.float32

## Range

In [ ]:
# Creating a range of tensors
torch.range(0,10) #deprecated

<ipython-input-23-fbd2cbd5c0c4>:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0,10) #deprecated


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [ ]:
#arange
one_to_ten = torch.arange(1,11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
one_to_thousand = torch.arange(start = 1, end = 1000, step = 100)
one_to_thousand

tensor([  1, 101, 201, 301, 401, 501, 601, 701, 801, 901])

In [ ]:
ten_zeros = torch.zeros_like(input= one_to_thousand)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

##Tensor Datatypes

In [ ]:
#torch.float16
#torch.float32
#Create a float32 tensor 
float_tensor = torch.tensor([3.0, 5.0, 9.0], 
                            dtype = None, 
                            device = None, 
                            requires_grad = False)

In [ ]:
float_tensor

tensor([3., 5., 9.])

In [ ]:
#Convert a float32 tensor to a float16 tensor
float_16_converted_tensor = float_tensor.type(torch.half)
float_16_converted_tensor

tensor([3., 5., 9.], dtype=torch.float16)

In [ ]:
#Multiply them together
float_16_converted_tensor*float_tensor

tensor([ 9., 25., 81.])

In [ ]:
#Create an integer tensor
int_32_tensor = torch.tensor([5, 8, 10], 
                             dtype = torch.int32,
                             device = None,
                             requires_grad = False)

In [ ]:
#Create a long tensor
int_long_tensor = torch.tensor([5, 8, 10], 
                             dtype = torch.long,
                             device = None,
                             requires_grad = False)

In [ ]:
#Multiply them together
int_32_tensor*int_long_tensor

tensor([ 25,  64, 100])

In [ ]:
#Comparing size() and shape

some_tensor = torch.rand(3,4)
some_tensor.size(), some_tensor.shape, some_tensor.dtype, some_tensor.device

(torch.Size([3, 4]), torch.Size([3, 4]), torch.float32, device(type='cpu'))

In [ ]:
some_tensor.type(torch.half)

tensor([[0.4360, 0.7773, 0.7686, 0.7124],
        [0.2390, 0.6807, 0.2937, 0.9536],
        [0.0623, 0.3330, 0.5942, 0.7939]], dtype=torch.float16)

## Manipulating Tensors


In [ ]:
#Addition
tensor1 = torch.tensor([1,2,3])
tensor1 + 10


tensor([11, 12, 13])

In [ ]:
#Multiplication
tensor1 *10

tensor([10, 20, 30])

In [ ]:
tensor1

tensor([1, 2, 3])

In [ ]:
tensor1-10

tensor([-9, -8, -7])

In [ ]:
# Multiply using in-built functions
torch.mul(tensor1, 10)

tensor([10, 20, 30])

In [ ]:
#add using built-in function
torch.add(tensor1, 10)

tensor([11, 12, 13])

In [ ]:
#Multiplication can be element-wise (scalar multiplication) or matrix multiiplication
#Element-wise
tensor1 * tensor1

tensor([1, 4, 9])

In [ ]:
#Matrix multiplication
torch.matmul(tensor1,tensor1)

tensor(14)

In [ ]:
%%time
sum=0
for i in range(len(tensor1)):
  sum += tensor1[i]*tensor1[i]
print(sum)

tensor(14)
CPU times: user 2.39 ms, sys: 0 ns, total: 2.39 ms
Wall time: 5.95 ms


In [ ]:
%%time
torch.matmul(tensor1,tensor1)

CPU times: user 88 µs, sys: 16 µs, total: 104 µs
Wall time: 110 µs


tensor(14)

In [ ]:
tensor1@tensor1 #same as torch.matmul

tensor(14)

In [ ]:
#inner dimensions must match for matmul
torch.matmul(torch.rand(2,3), torch.rand(3,2))

tensor([[0.8095, 0.9207],
        [0.5760, 0.6780]])

In [ ]:
#torch.mm is same as torch.matmul
tensor_a = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])
tensor_b = torch.tensor([[7,10],
                         [8,11],
                         [9,12]])
torch.mm(tensor_a,tensor_b.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [ ]:
print(f"Tensor A, Tensor B",{tensor_a.shape, tensor_b.shape})

Tensor A, Tensor B {torch.Size([3, 2])}


## Finding the min, max, mean, sum, etc (tensor aggregation)

In [ ]:
#Create a tensor 
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
x.dtype

torch.int64

In [ ]:
#Find the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [ ]:
#Find the max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [ ]:
# mean function needs a tensor of dtype float32
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

##Positional min and max

In [ ]:
#at Which position in the tensor does the minimum value occur?

torch.argmin(x)

tensor(0)

In [ ]:
#at which position in the tensor does the maximum value occur?
torch.argmax(x)

tensor(9)

##Reshaping, Stacking, Squeezing and Unsqueezing

In [ ]:
#reshape, view, stack, squeeze(remove 1 dimension), unsqueeze(add 1 dimension), permute
import torch
x = torch.arange(0, 10, 1)
x, x.shape

(tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([10]))

In [ ]:
#Reshaping
x_reshaped = x.reshape(10,1)
x_reshaped, x_reshaped.shape

(tensor([[0],
         [1],
         [2],
         [3],
         [4],
         [5],
         [6],
         [7],
         [8],
         [9]]), torch.Size([10, 1]))

In [ ]:
#Reshaping
x_reshaped = x.reshape(1,10)
x_reshaped, x_reshaped.shape

(tensor([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 10]))

In [ ]:
#Reshaping
x_reshaped = x.reshape(5,2)
x_reshaped, x_reshaped.shape

(tensor([[0, 1],
         [2, 3],
         [4, 5],
         [6, 7],
         [8, 9]]), torch.Size([5, 2]))

In [ ]:
#Reshaping
x_reshaped = x.reshape(2,5)
x_reshaped, x_reshaped.shape

(tensor([[0, 1, 2, 3, 4],
         [5, 6, 7, 8, 9]]), torch.Size([2, 5]))

In [ ]:
#Change the view (view shares the same memory as the tensor, so if you change z, x also changes)
z = x.view(1,10)
z, z.shape

(tensor([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 10]))

In [ ]:
z[:,0] = 5
z,x

(tensor([[5, 1, 2, 3, 4, 5, 6, 7, 8, 9]]),
 tensor([5, 1, 2, 3, 4, 5, 6, 7, 8, 9]))

In [ ]:
#Stack tensors on top of each other
x_stacked = torch.stack([x,x,x,x],dim = 1)

In [ ]:
x_stacked

tensor([[5, 5, 5, 5],
        [1, 1, 1, 1],
        [2, 2, 2, 2],
        [3, 3, 3, 3],
        [4, 4, 4, 4],
        [5, 5, 5, 5],
        [6, 6, 6, 6],
        [7, 7, 7, 7],
        [8, 8, 8, 8],
        [9, 9, 9, 9]])

In [ ]:
#Squeeze and Unsqueeze

x_reshaped = x.reshape(1,10)

In [ ]:

#Squeeze removes all single dimensions from the tensor
x_reshaped, x_reshaped.size()

(tensor([[5, 1, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 10]))

In [ ]:
y = x_reshaped.squeeze()
y

tensor([5, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
y.shape

torch.Size([10])

In [ ]:
print("Actual tensor: {}".format(x_reshaped))
print("Actual tensor shape: {}".format(x_reshaped.shape))

x_squeezed = x_reshaped.squeeze()
print("New tensor: {}".format(x_squeezed))
print("Actual tensor: {}".format(x_squeezed.shape))

Actual tensor: tensor([[5, 1, 2, 3, 4, 5, 6, 7, 8, 9]])
Actual tensor shape: torch.Size([1, 10])
New tensor: tensor([5, 1, 2, 3, 4, 5, 6, 7, 8, 9])
Actual tensor: torch.Size([10])


In [ ]:
#Unsqueeze adds a single dimension to the target tensor at a specific dim

In [ ]:
print("Squeezed tensor: {}".format(x_squeezed))
print("Squeezed tensor shape: {}".format(x_squeezed.shape))
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print("New tensor: {}".format(x_unsqueezed))
print("New tensor shape: {}".format(x_unsqueezed.shape))

Squeezed tensor: tensor([5, 1, 2, 3, 4, 5, 6, 7, 8, 9])
Squeezed tensor shape: torch.Size([10])
New tensor: tensor([[5, 1, 2, 3, 4, 5, 6, 7, 8, 9]])
New tensor shape: torch.Size([1, 10])


In [ ]:
print("Squeezed tensor: {}".format(x_squeezed))
print("Squeezed tensor shape: {}".format(x_squeezed.shape))
x_unsqueezed = x_squeezed.unsqueeze(dim=1)
print("New tensor: {}".format(x_unsqueezed))
print("New tensor shape: {}".format(x_unsqueezed.shape))

Squeezed tensor: tensor([5, 1, 2, 3, 4, 5, 6, 7, 8, 9])
Squeezed tensor shape: torch.Size([10])
New tensor: tensor([[5],
        [1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]])
New tensor shape: torch.Size([10, 1])


In [ ]:
#torch.permute rearranges the dimensions of the target tensor in a specified order

x_original = torch.rand(size = (224,224,3)) #(height, width, colur channel)

x_permuted = x_original.permute(2, 0, 1) #shifts channels to 1st 

print("Original shape: {}".format(x_original.shape))
print("Permuted shape: {}".format(x_permuted.shape)) #(colur channel, height, width)

Original shape: torch.Size([224, 224, 3])
Permuted shape: torch.Size([3, 224, 224])


In [ ]:
x_original[0,0,0] = 5
x_original[0,0,0], x_permuted[0,0,0]

(tensor(5.), tensor(5.))

##Indexing 

In [ ]:
#Create a tensor
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]), torch.Size([1, 3, 3]))

In [ ]:
x[0]


tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
x[0][0], x[0,0]

(tensor([1, 2, 3]), tensor([1, 2, 3]))

In [ ]:
x[0][1][1], x[0,0,0]

(tensor(5), tensor(1))

In [ ]:
x[0][2][2]

tensor(9)

In [ ]:
x[:,:,1]

tensor([[2, 5, 8]])

In [ ]:
#Demostrates the difference between using 0,1,1 and :1,1
x[:,1,1], x[0,1,1]

tensor([5])

In [ ]:
#Index on x to return 9
x[:,2,2],x[:,:,2]

(tensor([9]), tensor([[3, 6, 9]]))

## Numpy to Tensor

In [ ]:
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
array.dtype, tensor.dtype

(dtype('float64'), torch.float64)

In [ ]:
ten = torch.arange(1.0,8.0)
ten.dtype
numpy_ten = ten.numpy()
ten, numpy_ten

(tensor([1., 2., 3., 4., 5., 6., 7.]),
 array([1., 2., 3., 4., 5., 6., 7.], dtype=float32))

##Reproducibility (seeds)


In [ ]:
tensor_A = torch.rand(3,3)
tensor_B = torch.rand(3,3)
print(tensor_A)
print(tensor_B)
print(tensor_A == tensor_B)

tensor([[0.1332, 0.9346, 0.5936],
        [0.8694, 0.5677, 0.7411],
        [0.4294, 0.8854, 0.5739]])
tensor([[0.2666, 0.6274, 0.2696],
        [0.4414, 0.2969, 0.8317],
        [0.1053, 0.2695, 0.3588]])
tensor([[False, False, False],
        [False, False, False],
        [False, False, False]])


In [ ]:
import torch 
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
tensor_A = torch.rand(3,3)

torch.manual_seed(RANDOM_SEED)
tensor_B = torch.rand(3,3)

print(tensor_A)
print(tensor_B)
print(tensor_A == tensor_B)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009],
        [0.2566, 0.7936, 0.9408]])
tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009],
        [0.2566, 0.7936, 0.9408]])
tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])


##Running Tensors and Pytorch Objects in GPUs


In [ ]:
#Check GPU access
import torch
torch.cuda.is_available()

False

In [ ]:
#Set up device-agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cpu'

In [ ]:
#Count GPUs
torch.cuda.device_count()

/usr/local/lib/python3.8/dist-packages/torch/cuda/__init__.py:497: UserWarning: Can't initialize NVML
  warnings.warn("Can't initialize NVML")


0

In [ ]:
#Putting tensors and models to GPUs
tensor = torch.tensor([1,2,3])

#Tensor not on GPU
print(tensor, tensor.device)


tensor([1, 2, 3]) cpu


In [ ]:
#Move tensor to GPU if available
tensor_on_gpu = tensor.to(device)
tensor_on_gpu, tensor_on_gpu.device

(tensor([1, 2, 3]), device(type='cpu'))

In [ ]:
#Move tensor to CPU
tensor_back_on_CPU = tensor_on_gpu.cpu().numpy()